service: serverless-plugin-rust-hello-world

provider:
  name: aws
  stage: dev
  runtime: provided.al2
  region: us-east-1
  versionFunctions: false
  architecture: arm64

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!.serverless/**'
    - '!node_modules/**'

configValidationMode: error

functions:
  hello-world:
    description: Rust hello world
    handler: hello-world
    events:
      - http:
          path: '/hello/{string}'
          method: get
          request:
            parameters:
              paths:
                string: true

plugins:
  - serverless-plugin-rust
